class Project {
  final String name;
  final String description;
  final List<String> image;
  final String link;
  Project(this.name, this.description, this.image, this.link);
}

List<Project> projectList = [
  Project(
    'Our-Clothes-Store',
    " A Flutter application used to facilitate transactions between sellers and buyers in stores.",
    [
      'assets/images/e-commerce (1).jpeg',
      'assets/images/e-commerce (2).jpeg',
      'assets/images/e-commerce (3).jpeg',
      'assets/images/e-commerce (4).jpeg',
      'assets/images/e-commerce (5).jpeg',
      'assets/images/e-commerce (6).jpeg',
      'assets/images/e-commerce (7).jpeg',
      'assets/images/e-commerce (8).jpeg',
      'assets/images/e-commerce (9).jpeg',
      'assets/images/e-commerce (10).jpeg',
      'assets/images/e-commerce (11).jpeg',
      'assets/images/e-commerce (12).jpeg',
      'assets/images/e-commerce (13).jpeg',
      'assets/images/e-commerce (14).jpeg',
      'assets/images/e-commerce (15).jpeg',
      'assets/images/e-commerce (16).jpeg',
      'assets/images/e-commerce (17).jpeg',
      'assets/images/e-commerce (18).jpeg',
      'assets/images/e-commerce (19).jpeg',
      'assets/images/e-commerce (20).jpeg',
      'assets/images/e-commerce (21).jpeg',
      'assets/images/e-commerce (22).jpeg',
      'assets/images/e-commerce (23).jpeg',
      'assets/images/e-commerce (24).jpeg',
    ],
    'https://github.com/MAHMOUDAHMED175/our_clothes_store',
  ),
  Project(
    'ERP-system-app',
    "To control the storage and sorting of products and goods in warehouses",
    [
      'assets/images/erp (1).jpeg',
      'assets/images/erp (2).jpeg',
      'assets/images/erp (3).jpeg',
      'assets/images/erp (4).jpeg',
      'assets/images/erp (5).jpeg',
      'assets/images/erp (6).jpeg',
      'assets/images/erp (7).jpeg',
      'assets/images/erp (8).jpeg',
      'assets/images/erp (9).jpeg',
      'assets/images/erp (10).jpeg',
      'assets/images/erp (11).jpeg',
      'assets/images/erp (12).jpeg',
      'assets/images/erp (13).jpeg',
      'assets/images/erp (14).jpeg',
      'assets/images/erp (15).jpeg',
      'assets/images/erp (16).jpeg',
      'assets/images/erp (17).jpeg',
      'assets/images/erp (18).jpeg',
      'assets/images/erp (19).jpeg',
      'assets/images/erp (20).jpeg',
      'assets/images/erp (21).jpeg',
      'assets/images/erp (22).jpeg',
      'assets/images/erp (23).jpeg',
      'assets/images/erp (24).jpeg',
      'assets/images/erp (25).jpeg',
      'assets/images/erp (26).jpeg',
      'assets/images/erp (27).jpeg',
      'assets/images/erp (28).jpeg',
      'assets/images/erp (29).jpeg',
      'assets/images/erp (30).jpeg',
    ],
    '',
  ),
  Project(
    'social-app',
    " A social networking application that enables chatting with friends and viewing their posts.",
    [
      'assets/images/face (1).png',
      'assets/images/face (2).png',
      'assets/images/face (3).png',
      'assets/images/face (4).png',
      'assets/images/face (5).png',
      'assets/images/face (6).png',
      'assets/images/face (7).png',
      'assets/images/face (8).png',
      'assets/images/face (9).png',
      'assets/images/face.png',
    ],
    '',
  ),
  Project(
    'la-music-app',
    "To import and play local music and videos.",
    [
      'assets/images/music (1).png',
      'assets/images/music (2).png',
      'assets/images/music (3).png',
      'assets/images/music (4).png',
      'assets/images/music (5).png',
      'assets/images/music (6).png',
      'assets/images/music (7).png',
      'assets/images/music (8).png',
      'assets/images/music (9).png',
    ],
    '',
  ),
  Project(
    'news-desktop,mobile,web-app',
    "To know all the local and international news from arts, technology, etc",
    [
      'assets/images/news1.png',
      'assets/images/newss (1).png',
      'assets/images/newss (2).png',
      'assets/images/newss (3).png',
    ],
    '',
  ),
  Project(
    'note-todo-task-app',
    "Managing and implementing daily tasks",
    [
      'assets/images/noooote (1).jpeg',
      'assets/images/noooote (2).jpeg',
      'assets/images/noooote (3).jpeg',
      'assets/images/note (1).png',
      'assets/images/note (2).png',
      'assets/images/note (3).png',
      'assets/images/note (4).png',
      'assets/images/note (5).png',
      'assets/images/note (6).png',
      'assets/images/note (7).png',
      'assets/images/note (8).png',
      'assets/images/note (9).png',
      'assets/images/note (10).png',
      'assets/images/note (11).png',
      'assets/images/note (12).png',
      'assets/images/note (13).png',
      'assets/images/note0.png',
    ],
    '',
  ),
  Project(
    'type-of-payments',
    "Stripe-paypal-paymob-visa",
    [
      'assets/images/payment.png',
      'assets/images/payment (1).png',
      'assets/images/payment (2).png',
      'assets/images/payment (3).png',
      'assets/images/payment (4).png',
      'assets/images/payment (5).png',
      'assets/images/payment (6).png',
      'assets/images/payment (7).png',
    ],
    '',
  ),
  Project(
    'quotes-app',
    " A Flutter application designed to display the latest quotes from scholars, celebrities, and others.",
        [
      'assets/images/qoute (1).png',
      'assets/images/qoute (2).png',
      'assets/images/qoute (3).png',
      'assets/images/qoute (4).png',
      'assets/images/qoutes1.png',
      'assets/images/qoutes2.png',
      'assets/images/qoutes3.png',
      'assets/images/qoute (5).png',
    ],
    'https://github.com/MAHMOUDAHMED175/QuotesSay',
  ),
  Project(
    'quran',
    "To read the Holy Qur’an in more than one line and search the verses",
    [
      'assets/images/quran (1.png',
      'assets/images/quran (1).png',
      'assets/images/quran (2).png',
      'assets/images/quran (3).png',
      'assets/images/quran (4).png',
      'assets/images/quran (5).png',
      'assets/images/quran.png',
    ],
    '',
  ),
  Project(
    'resturant-desktop-ui',
    "awesome ui for resturant services",
    [
      'assets/images/reasturant 7_10_2024 2_07_25 PM.png',
      'assets/images/reasturant 7_10_2024 2_07_58 PM.png',
    ],
    '',
  ),
  Project(
    'tertits-game-app',
    "flutter game app",
    [
      'assets/images/tertits (1).png',
      'assets/images/tertits (2).png',
    ],
    '',
  ),
  Project(
    'weather-app',
    "An application to retrieve weather conditions for different cities or governorates, such as Cairo.",
    [
      'assets/images/weather (1).png',
      'assets/images/weather (2).png',
      'assets/images/weather (3).png',
      'assets/images/weather (4).png',
      'assets/images/weather (5).png',
      'assets/images/weather (6).png',
      'assets/images/weather (7).png',
      'assets/images/weather.png',
    ],
    '',
  ),
  Project(
    'video-from-youtube-app',
    "Extract specific YouTube channel data and display videos in parallel.",
    [
      'assets/images/WhatsApp Image 2024-07-10 at 12.18.13 PM.jpeg',
      'assets/images/WhatsApp Image 2024-07-10 at 12.18.14 PM (1).jpeg',
      'assets/images/WhatsApp Image 2024-07-10 at 12.18.14 PM.jpeg',
    ],
    '',
  ),
  Project(
    'zoom-app',
    "To carry out a voice and video communication process between users",
    [
      'assets/images/zoom (1).png',
      'assets/images/zoom (2).png',
      'assets/images/zoom (3).png',
      'assets/images/zoom (4).png',
      'assets/images/zoom (5).png',
      'assets/images/zoom (6).png',
      'assets/images/zoom (7).png',
    ],
    '',
  ),
];
